### ISSUE TITLE
v4.0.0-beta.4 - [merged]

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-gui#138]
_Merges v4.0.0-beta.4 -> master_

Features:

* [x] Improved Login page design with animations
* [x] Updated About page #103
* [x] Fix mandatory login redirect on unauthenticated case
* [x] Added a button to periodically refresh the home page #104 
* [x] Fix submit written text on changing other options #102 
* [x] Hover all the experiment cards and not just the header on the home page
* [x] Allow multiple select jobs to generate `setstatus` commands
* [x] Migrated from vis-network to Cytoscape
* [x] Add multiple select in graph/tree view
* [x] Add select by status option in the graph view
* [x] Add page size options on the experiment search

Waiting to get feedback from the CES and Climate DT users to extend the scope of this version

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>64174f51 - update experiment card hover</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23102&start_sha=ddae55794cb27dfb33203ed47824c5b6ed2f3f12)

**Comment by LuiggiTenorioK** [comment]
marked the checklist item **Hover all the experiment cards and not just the header on the home page** as completed

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>8b444955 - added JobBasket component</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23175&start_sha=64174f5192976829e24e1821cd17fbf6103d7115)

**Comment by LuiggiTenorioK** [comment]
Preview of the Multiple Job Selection feature:

![Screencast_from_22-03-24_13_44_05](https://earth.bsc.es/gitlab/es/autosubmit-gui/uploads/ff3cd6d6136b183026f21f2acc610101/Screencast_from_22-03-24_13_44_05.webm)

**Comment by LuiggiTenorioK** [comment]
marked the checklist item **Allow multiple select jobs to generate `setstatus` commands** as completed

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>488cef2d - improve graph focus</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23373&start_sha=8b444955a617fefac4dbcf62f9f5277400de1257)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>39ecd378 - add Cytoscape to the Graph View</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23491&start_sha=488cef2d1a0788e1295d869e90ba3bedd55ef047)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>b239aa6b - fix fancy tree multiple select</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23493&start_sha=39ecd378b7c23adc1e28f09e9a7d7eb0a8cf2932)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>ef80dbb4 - add bottom panel in graph view</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23501&start_sha=b239aa6ba649a9f17a91790055c57dcc27e785cd)

**Comment by LuiggiTenorioK** [comment]
Migrated to Cytoscape and added a bottom panel to the graph view

![Screencast_from_03-04-24_12_09_14](https://earth.bsc.es/gitlab/es/autosubmit-gui/uploads/086eefa08e5c0726bb9231d2f4b1aca2/Screencast_from_03-04-24_12_09_14.webm)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>a20e24d4 - Home page improvements</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23519&start_sha=ef80dbb47d6538fed653a1101326b9fc6d27c743)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>318434e5 - select by status in graph view</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23522&start_sha=a20e24d4853aae465487384ec8b94befdd5e019d)

**Comment by LuiggiTenorioK** [comment]
marked the checklist item **Add select by status option in graph view** as completed

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>67be9a47 - fix graph multiple select performance issue</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23576&start_sha=318434e55b9fa50c011ab60251e73cc08db47563)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>a5870031 - refactor fancy tree</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23598&start_sha=67be9a476213389c1ec979ab7b2f0b933ea915d6)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>103282a0 - add job history modal</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23667&start_sha=a58700310e84b89ee2fca4b94a3296a18503ba0d)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>e0b654fd - improvements in multiple selection</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23670&start_sha=103282a02799a86dfdf0df82aa61296652588b8e)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>764c98f5 - add help text in graph viewport</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23704&start_sha=e0b654fd561c8c675282b1cdaf031fbb9f7a9a38)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>626e06d6 - add localstorage save to bottom panel</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23705&start_sha=764c98f5208eee08481fb9fe6ab4d8063bdc535a)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>e2769c34 - multiple ui improvements</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23706&start_sha=626e06d6771fab40373c1bd4a516e391f1a5cdb6)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>192eb3e2 - adding react hook form</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23732&start_sha=e2769c34e392134ceb9b683b8f4105fa76362ad9)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>9bc5b88a - fix dropdown in experiment card</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23737&start_sha=192eb3e2e8e1f8a85bc113d8be17993e87139c61)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>178342eb - add more filters in exp search</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23796&start_sha=9bc5b88aea069da7c67a4d1884ca940b13508f09)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>0145ea9f - add wrapper visualization</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23812&start_sha=178342ebd6c3714b09988a597f317dce52a9f62f)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>fdd662a2 - update style of configuration view</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23877&start_sha=0145ea9f91c0ee7de6275172497fae62b4254222)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>a936f4f5 - add tests for graph view</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23901&start_sha=fdd662a2df00e3fbf7fb389152dda4c106e6cd14)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>9a3be77a - add tree, performance and stats tests</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23921&start_sha=a936f4f598767827dd658a14cadca738c3caafcc)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>ec7e52d8 - improve performance tables</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23925&start_sha=9a3be77a9b2390c15d55ef7723573ef85b709c9a)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>8f464c89 - improve navbar resposiveness</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23927&start_sha=ec7e52d8da0314a8b352f71256368383825612b7)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>e15dc8bb - add statistics tooltip</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=23983&start_sha=8f464c8927d42af1ab0f4ba0402fd32cfdcb9c81)

**Comment by LuiggiTenorioK** [comment]
added 7 commits

<ul><li>3c0cc06e - initial docs</li><li>e28738be - old pages review</li><li>bd5bb559 - add installation instructions</li><li>b21c033a - add landing page</li><li>a2f5fb4a - add .readthedocs.yaml</li><li>75e462ca - add sponsor logo option</li><li>ca559ecf - Merge branch &#39;read-the-docs&#39; into &#39;v4.0.0-beta.4&#39;</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=24415&start_sha=e15dc8bba8344b5e7a4127104bf85d2b9bef61c0)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>b22d4183 - lint fixes &amp; improvements</li></ul>

[Compare with previous version](/gitlab/es/autosubmitreact/-/merge_requests/19/diffs?diff_id=24449&start_sha=ca559ecfbcd0c94c5f81d51dd7bce60b3d27f1e1)

**Comment by LuiggiTenorioK** [comment]
added 1 commit

<ul><li>af769c17 - improve copy to clipboard button</li></ul>

[Compare with previous version](/gitlab/es/autosubmit-gui/-/merge_requests/19/diffs?diff_id=24624&start_sha=b22d418308aa346043233fe16bc2aceb71b23d1a)

**Comment by LuiggiTenorioK** [comment]
approved this merge request

**Comment by LuiggiTenorioK** [comment]
mentioned in commit fb3f3c815fab89807049dcc3628ea344956d8d6f
